name: Toci
favicon: null
layout_spectrum: 0.33625
typography_spectrum: 0.33113
title: toci.xyz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1873c4'
    - '#e3f6fd'
    - '#8cdafe'
    - '#85b0d3'
    - '#4e6a80'
  brandStrength: 0.3125
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
