name: Toci
favicon: null
layout_spectrum: 0.008776561357080936
typography_spectrum: 0.3261308332439512
title: toci.xyz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1873c4'
    - '#e3f6fd'
    - '#8cdafe'
    - '#85b0d3'
    - '#4e6a80'
  brandStrength: 0.1875
  lightness: 0.017405792139470577
  saturation: 0.7545020210091025
  rhythmicContrast: 0.28206017799675465
purpose: []
